apiVersion: v1
kind: Service
metadata:
  name: {{service.name}}
spec:
  type: ClusterIP
  selector:
    app: {{build.name}}
  ports:
  - protocol: {{service.protocol|default('TCP')}}
    port: {{service.port|default('80')}}
    targetPort: {{service.targetPort|default('80')}}
