apiVersion: v1
kind: Service
metadata:
  name: {{service.name}}
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  {{build.name}}_mapping
      prefix: /
      service: {{service.name}}:{{service.port|default('8080')}}
      use_websocket: true
      timeout_ms: 100000
      {%- if "weight" in build.profile %}
      weight: {{build.profile.weight}}
      {%- endif %}
spec:
  type: ClusterIP
  selector:
    app: {{build.name}}
  ports:
  - protocol: {{service.protocol|default('TCP')}}
    port: {{service.port|default('8080')}}
    targetPort: {{service.targetPort|default('80')}}
