apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv-0
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: postgresql
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /kubernetes/postgresql
    server: 127.0.0.1