apiVersion: v1
kind: Service
metadata:
  name: {{build.name}}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  AuthService
      name:  authentication
      auth_service: "{{build.name}}:{{service.port|default('8080')}}"
      path_prefix: "/auth"
      allowed_headers:
      - "x-jwt-session"
spec:
  type: ClusterIP
  selector:
    app: {{build.name}}
  ports:
  - protocol: {{service.protocol|default('TCP')}}
    port: {{service.port|default('80')}}
    targetPort: {{service.targetPort|default('80')}}
