kind: Service
apiVersion: v1
metadata:
  name: icinga-web
spec:
  type: NodePort
  selector:
    app: icinga
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30080
  - name: https
    protocol: TCP
    port: 8443
    targetPort: 443
    nodePort: 30443
---
kind: Service
apiVersion: v1
metadata:
  name: icinga-api
spec:
  selector:
    app: icinga
  ports:
  - name: api
    protocol: TCP
    port: 5665
    targetPort: 5665
