apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  frontend_mapping
      prefix: /
      service: frontend"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: frontend
  selector:
    app: frontend