apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-0
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: kafka
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /kubernetes/kafka/broker0
    server: 127.0.0.1
---