CREATE TABLE HOSTS (
id INT NOT NULL,
hostName VARCHAR (75) NOT NULL,
description VARCHAR (150) DEFAULT NULL,
icon VARCHAR (75) DEFAULT NULL ,
PRIMARY KEY (id),
);

CREATE TABLE SERVICES (
id INT NOT NULL,
serviceName VARCHAR (75) NOT NULL,
hostID INT NOT NULL,
type VARCHAR (10) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (hostID) REFERENCES HOSTS(id)
);