CREATE TABLE HOSTS (
  id INT NOT NULL,
  hostName VARCHAR (150) NOT NULL,
  description TEXT DEFAULT NULL,
  icon TEXT DEFAULT NULL,
  PRIMARY KEY (id)
);


CREATE TABLE SERVICES (
  id INT NOT NULL,
  serviceName VARCHAR (150) NOT NULL,
  hostID INT NOT NULL,
  type VARCHAR (10) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (hostID) REFERENCES HOSTS(id)
);

