apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  AuthService
      name:  authentication
      auth_service: "auth-service:80"
      path_prefix: "/auth"
      allowed_headers:
      - "x-jwt-session"
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
  - port: 80
    name: http-auth-service
    targetPort: 80
