apiVersion: skaffold/v1alpha5
kind: Config
build:
  tagPolicy:
    gitCommit: {}
    
  artifacts:
  - image: localhost:5000/frontend
    context: ./frontend/
deploy:
  kubectl:
    manifests:
    - ./frontend/kubernetes/*
