/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package influxdb.listener;

public class App {
    public static void main(String[] args) throws InterruptedException {
        while (true) {
            System.out.println("Hello");
            Thread.sleep(10000);
        }
    }
}
